name: Validate Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 'main'

jobs:
  code-formatting:
    name: "Check Code Formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Prettier and Apex Prettier Plugin
        run: |
          npm install

      - name: Run Prettier to check code format
        run: npm run prettier:verify

  code-analysis:
    name: "Run Code Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install SFDX CLI and Source Code Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run Source Code Scanner
        uses: mitchspano/sfdx-scan-pull-request@v0.1.16
        with:
          pmdconfig: ruleset.xml

  deploy:
    name: Deployment
    needs: [code-formatting, code-analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Authenticate to Salesforce using Auth URL
        run: echo "${{ secrets.SF_AUTH_URL }}" > sfdx_auth_url.txt && sf org login sfdx-url --sfdx-url-file sfdx_auth_url.txt --set-default --alias cpxdev

      - name: Deploy to Salesforce
        run: |
          # Deploy source to Salesforce org
          sf project deploy start --target-org cpxdev --async --concise --test-level NoTestRun